{% set version = '0.1.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fastymd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fastymd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fastymd/fastymd_{{ version }}.tar.gz
  sha256: 0baaddda31a918501484ca0b07d6faa2b67d460c368a0affbc8f9a870bc8254f

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ stdlib('c') }}              # [not win]
    - {{ stdlib('m2w64_c') }}        # [win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('fastymd')"           # [not win]
    - "\"%R%\" -e \"library('fastymd')\""  # [win]

about:
  home: https://timtaylor.codeberg.page/fastymd/
  dev_url: https://codeberg.org/TimTaylor/fastymd
  license: GPL-3.0-only
  summary: A collection of utility functions for working with Year Month Day objects. Includes
    functions for fast parsing of numeric and character input based on algorithms described
    in Hinnant, H. (2021) <https://howardhinnant.github.io/date_algorithms.html> as
    well as a branchless calculation of leap years by Jerichaux (2025) <https://stackoverflow.com/a/79564914>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: fastymd
# Title: Fast Utilities for 'Year Month Day' Objects
# Version: 0.1.2
# Authors@R: c( person( given   = "Tim", family  = "Taylor", role    = c("aut", "cre"), email   = "tim.taylor@hiddenelephants.co.uk", comment = c(ORCID = "0000-0002-8587-7113") ), person( given   = "Howard", family  = "Hinnant", role    = "aut", comment = "Author of underlying algorithms for calculating Epoch days to Calendar days and vice versa" ), person( "jerichaux", role    = "aut", comment = "Author of included branchless leap year calculation" ) )
# Description: A collection of utility functions for working with Year Month Day objects. Includes functions for fast parsing of numeric and character input based on algorithms described in Hinnant, H. (2021) <https://howardhinnant.github.io/date_algorithms.html> as well as a branchless calculation of leap years by Jerichaux (2025) <https://stackoverflow.com/a/79564914>.
# License: GPL-3
# URL: https://timtaylor.codeberg.page/fastymd/
# BugReports: https://codeberg.org/TimTaylor/fastymd/issues
# Encoding: UTF-8
# Suggests: fasttime, lubridate, microbenchmark, tinytest, ymd, litedown
# Depends: R (>= 4.2.0)
# VignetteBuilder: litedown
# RoxygenNote: 7.3.2
# Config/testthat/load-all: list(export_all = FALSE, helpers = FALSE)
# NeedsCompilation: yes
# Packaged: 2025-04-24 21:51:32 UTC; tim
# Author: Tim Taylor [aut, cre] (<https://orcid.org/0000-0002-8587-7113>), Howard Hinnant [aut] (Author of underlying algorithms for calculating Epoch days to Calendar days and vice versa), jerichaux [aut] (Author of included branchless leap year calculation)
# Maintainer: Tim Taylor <tim.taylor@hiddenelephants.co.uk>
# Repository: CRAN
# Date/Publication: 2025-04-25 12:50:02 UTC
